Repository slack-samples/deno-hello-world, pull requests merged in 2022-09, with the labels that each got.

#6 Update README
  README.md
Labels: documentation

#8 [#7] Update function title and description
  functions/greeting_function.ts
Labels: bug

#9 Tweak CI build settings, license file, and README
  .github/workflows/deno.yml
  LICENSE
  README.md
Labels: documentation, enhancement
